// ISO-3166 alpha-2 -> Nombre en español
export const COUNTRY_NAMES_ES: Record<string, string> = {
  AF: "Afganistán", AL: "Albania", DZ: "Argelia", AD: "Andorra", AO: "Angola",
  AR: "Argentina", AM: "Armenia", AU: "Australia", AT: "Austria", AZ: "Azerbaiyán",
  BS: "Bahamas", BH: "Baréin", BD: "Bangladés", BB: "Barbados", BY: "Bielorrusia",
  BE: "Bélgica", BZ: "Belice", BJ: "Benín", BM: "Bermudas", BT: "Bután",
  BO: "Bolivia", BA: "Bosnia y Herzegovina", BW: "Botsuana", BR: "Brasil",
  BN: "Brunéi", BG: "Bulgaria", BF: "Burkina Faso", BI: "Burundi",
  KH: "Camboya", CM: "Camerún", CA: "Canadá", CV: "Cabo Verde", CF: "República Centroafricana",
  TD: "Chad", CL: "Chile", CN: "China", CO: "Colombia", KM: "Comoras",
  CG: "República del Congo", CD: "República Democrática del Congo", CR: "Costa Rica",
  CI: "Costa de Marfil", HR: "Croacia", CU: "Cuba", CY: "Chipre", CZ: "República Checa",
  DK: "Dinamarca", DJ: "Yibuti", DM: "Dominica", DO: "República Dominicana",
  EC: "Ecuador", EG: "Egipto", SV: "El Salvador", GQ: "Guinea Ecuatorial",
  ER: "Eritrea", EE: "Estonia", SZ: "Esuatini", ET: "Etiopía",
  FJ: "Fiyi", FI: "Finlandia", FR: "Francia", TF: "Tierras Australes Francesas",
  GA: "Gabón", GM: "Gambia", GE: "Georgia", DE: "Alemania", GH: "Ghana",
  GI: "Gibraltar", GR: "Grecia", GL: "Groenlandia", GD: "Granada",
  GT: "Guatemala", GN: "Guinea", GW: "Guinea-Bisáu", GY: "Guyana",
  HT: "Haití", HN: "Honduras", HK: "Hong Kong", HU: "Hungría",
  IS: "Islandia", IN: "India", ID: "Indonesia", IR: "Irán", IQ: "Irak",
  IE: "Irlanda", IL: "Israel", IT: "Italia",
  JM: "Jamaica", JP: "Japón", JO: "Jordania",
  KZ: "Kazajistán", KE: "Kenia", KP: "Corea del Norte", KR: "Corea del Sur",
  KW: "Kuwait", KG: "Kirguistán",
  LA: "Laos", LV: "Letonia", LB: "Líbano", LS: "Lesoto", LR: "Liberia",
  LY: "Libia", LI: "Liechtenstein", LT: "Lituania", LU: "Luxemburgo",
  MG: "Madagascar", MW: "Malaui", MY: "Malasia", MV: "Maldivas", ML: "Malí",
  MT: "Malta", MH: "Islas Marshall", MR: "Mauritania", MU: "Mauricio",
  MX: "México", MD: "Moldavia", MC: "Mónaco", MN: "Mongolia", ME: "Montenegro",
  MA: "Marruecos", MZ: "Mozambique", MM: "Birmania",
  NA: "Namibia", NP: "Nepal", NL: "Países Bajos", NC: "Nueva Caledonia",
  NZ: "Nueva Zelanda", NI: "Nicaragua", NE: "Níger", NG: "Nigeria",
  MK: "Macedonia del Norte", NO: "Noruega",
  OM: "Omán",
  PK: "Pakistán", PA: "Panamá", PG: "Papúa Nueva Guinea", PY: "Paraguay",
  PE: "Perú", PH: "Filipinas", PL: "Polonia", PT: "Portugal",
  QA: "Catar",
  RO: "Rumanía", RU: "Rusia", RW: "Ruanda",
  WS: "Samoa", SA: "Arabia Saudita", SN: "Senegal", RS: "Serbia",
  SL: "Sierra Leona", SG: "Singapur", SK: "Eslovaquia", SI: "Eslovenia",
  SB: "Islas Salomón", SO: "Somalia", ZA: "Sudáfrica", SS: "Sudán del Sur",
  ES: "España", LK: "Sri Lanka", SD: "Sudán", SR: "Surinam", SE: "Suecia",
  CH: "Suiza", SY: "Siria",
  TW: "Taiwán", TJ: "Tayikistán", TZ: "Tanzania", TH: "Tailandia",
  TL: "Timor Oriental", TG: "Togo", TO: "Tonga", TT: "Trinidad y Tobago",
  TN: "Túnez", TR: "Turquía", TM: "Turkmenistán", TV: "Tuvalu",
  UG: "Uganda", UA: "Ucrania", AE: "Emiratos Árabes Unidos", GB: "Reino Unido",
  US: "Estados Unidos", UY: "Uruguay", UZ: "Uzbekistán",
  VU: "Vanuatu", VE: "Venezuela", VN: "Vietnam",
  YE: "Yemen", ZM: "Zambia", ZW: "Zimbabue",
};

export function getCountryNameES(iso: string, fallback?: string): string {
  return COUNTRY_NAMES_ES[iso] ?? fallback ?? iso;
}
